# Generated by Django 3.2.5 on 2021-12-15 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=2000)),
                ('address2', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=200)),
                ('distinct', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
