# Generated by Django 3.2.5 on 2021-12-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessentity',
            old_name='distinct',
            new_name='region',
        ),
    ]
