# Generated by Django 3.2.5 on 2021-12-20 02:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0003_auto_20211217_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contract_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('address2', models.CharField(blank=True, max_length=2000, null=True)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('address2', models.CharField(blank=True, max_length=2000, null=True)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BusinessEntity',
        ),
        migrations.AddField(
            model_name='contract',
            name='external_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_contracts.externalentity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='internal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_contracts.internalentity'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('external_entity', 'internal_entity')},
        ),
    ]
