# Generated by Django 3.2.5 on 2021-12-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0004_auto_20211220_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_extension',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('external_entity', 'internal_entity', 'contract_date', 'contract_extension')},
        ),
    ]
