# Generated by Django 3.2.5 on 2021-12-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0005_auto_20211220_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='external_entity',
            new_name='external_entity_id',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='internal_entity',
            new_name='internal_entity_id',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('external_entity_id', 'internal_entity_id', 'contract_date', 'contract_extension')},
        ),
    ]
