# Generated by Django 3.2.5 on 2021-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0006_auto_20211220_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_extension',
            field=models.IntegerField(default=0),
        ),
    ]
