# Generated by Django 3.2.5 on 2021-12-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0007_alter_contract_contract_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_extension',
            field=models.IntegerField(default=''),
        ),
    ]
