# Generated by Django 3.2.5 on 2021-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0008_alter_contract_contract_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_extension',
            field=models.CharField(default='', max_length=4),
        ),
    ]
