# Generated by Django 3.2.5 on 2021-12-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_contracts', '0009_alter_contract_contract_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='external_entity_id',
            new_name='external_entity',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='internal_entity_id',
            new_name='internal_entity',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('external_entity', 'internal_entity', 'contract_date', 'contract_extension')},
        ),
    ]
